const SET_MESSAGES = "SET_MESSAGES";

const WEATHER_DATA_FETCH_REQUESTED = "WEATHER_DATA_REQUESTED";
const WEATHER_DATA_FETCH_FAILED = "WEATHER_DATA_FETCH_FAILED";
const WEATHER_DATA_FETCH_SUCCEEDED = "WEATHER_DATA_FETCH_SUCCEEDED";

export {
  SET_MESSAGES,
  WEATHER_DATA_FETCH_REQUESTED,
  WEATHER_DATA_FETCH_FAILED,
  WEATHER_DATA_FETCH_SUCCEEDED,
};
